name: importaciones_week
description: Solución semanal — empresa de importación
publish_to: none
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
